### ISSUE TITLE
If this theme can support comments?

### ISSUE THREAD

**Issue by robustmaster** [MarcArmengou/100-bytes#4]
Very nice tiny theme. I wonder how to add comments supports.

**Comment by marcarmengou** [comment]
Thanks @robustmaster. The issue is that the comment styles, in order to look good everywhere, would cause the CSS size limit to increase.

Currently the CSS size is 82 bytes, so we could only use 18 bytes of CSS infromation to accomplish this.

**Comment by robustmaster** [comment]
@MarcArmengou Thanks for your reply. May be 200-byte theme can add this feature. lol

**Comment by marcarmengou** [comment]
@robustmaster actually there is the same problem, only 20 bytes of additional CSS information could be used there. Maybe the comment styles could be interesting for a new theme, larger than 200 bytes.

**Comment by robustmaster** [comment]
@MarcArmengou OK, I got it. Thank you, anyway.
